version: '2'
services:
  webpack:
    build:
      context: ./webpack
    image: webpack-react
    container_name: webpack-container
    ports:
      - "80:8080"
    volumes:
      - ./app/src:/app/src:ro
      - ./app/dist:/app/dist:z
